# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c597ff301b484beece4cc0e98b0db616bf39fd9cae145efbca8ac7cccbc487e1fb1dcab9adca5f514bced6259c6cf08b84c530041ea4fac3da14d6ec46973649

test:
  secret_key_base: 02ae012f9ca531392f08b70a3b0457cdb68fed1bdae7d2a909ee8ad606697525497a6610626ecd56ff7d70cd190267492059420d0aeb42b23fbf0275dec3a9c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
